stages:
  - stage: Zip
    dependsOn: []
    jobs:
      - job: Zip
        pool:
          vmImage: ubuntu-latest
        displayName: Zip app
        workspace:
          clean: all
        steps:
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.BinariesDirectory)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
            verbose: true

  - stage: STG
    displayName: STG
    jobs:
      - job: RunScript
        pool:
          vmImage: ubuntu-latest
        workspace:
          clean: all
        displayName: Run script
        steps:
          - script: echo Hello from staging!
            displayName: 'Run a one-line script'